name: ticket_management
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  # State management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Firebase
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1

  # Utilities
  equatable: ^2.0.7
  meta: ^1.15.0

  # Flutter SDK
  flutter:
    sdk: flutter

  # Testing
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

dev_dependencies:
  # Linting
  flutter_lints: ^5.0.0

  # Testing
  test: ^1.25.8

flutter:
  uses-material-design: true
