// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9jyxc2px2VPvWq_-emmXtbS7pVnTNp8',
    appId: '1:831645109181:web:517ef687a82a881412a0d4',
    messagingSenderId: '831645109181',
    projectId: 'techmind-test',
    authDomain: 'techmind-test.firebaseapp.com',
    storageBucket: 'techmind-test.firebasestorage.app',
    measurementId: 'G-GP71JFQ93B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm9jyxc2px2VPvWq_-emmXtbS7pVnTNp8',
    appId: '1:831645109181:android:897e5bc4dc3a277b12a0d4',
    messagingSenderId: '831645109181',
    projectId: 'techmind-test',
    storageBucket: 'techmind-test.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKDUorIuzCBccvVC58POg9EtC8eCd7xRs',
    appId: '1:831645109181:web:c1eb43744b33b21f12a0d4',
    messagingSenderId: '831645109181',
    projectId: 'techmind-test',
    authDomain: 'techmind-test.firebaseapp.com',
    storageBucket: 'techmind-test.firebasestorage.app',
    measurementId: 'G-HN873B0S0D',
  );
}
